[font]
size = 17.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[colors.primary]
foreground = "#feffff"
background = "#1c1c1c"

[colors.normal]
red="#e06c75"
green="#98c379"
yellow="#e5c07b"
blue="#61afef"
magenta="#c678dd"
cyan="#56b6c2"

[colors.bright]
red="#b2574b"
green="#78a557"
yellow="#ca9b6e"
blue="#518bbb"
magenta="#976ca5"
cyan="#46919a"

[colors.cursor]
cursor = "#feffff"
text = "#080200"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"

[cursor]
style = { shape = "Block", blinking = "Always" }

[keyboard]
bindings = [
    { key = "Enter", mods = "Command", action = "ToggleFullscreen"},
    { key = "Enter", mods = "Super", action = "ToggleFullscreen"},
    { key = "Backspace", mods = "Control", chars = "\u007f"},
]
